### ISSUE TITLE
Fix bug with deleted account

### ISSUE THREAD

**Issue by Forevka** [Forevka/Emcd#7]
when user deleted account they still can click on button with not existed account, and it produces error

`2021-03-21 15:22:34.554 | ERROR    | asyncio.base_events:default_exception_handler:1707 - Task exception was never retrieved
future: <Task finished name='Task-13006' coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=AttributeError("'NoneType' object has no attribute 'username'")>
Traceback (most recent call last):

> File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                     │         │     │                   │    │               │        └ True
                     │         │     │                   │    │               └ [<aiogram.types.update.Update object at 0x7fc46e6ad9a0>]
                     │         │     │                   │    └ <function Dispatcher.process_updates at 0x7fc46fde5b80>
                     │         │     │                   └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x7fc4716be370>
                     │         │     └ <method 'from_iterable' of 'itertools.chain' objects>
                     │         └ <class 'itertools.chain'>
                     └ <module 'itertools' (built-in)>
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
                 │       │       └ [<coroutine object Handler.notify at 0x7fc46f4f7c40>]
                 │       └ <function gather at 0x7fc471315430>
                 └ <module 'asyncio' from '/usr/local/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<aiogram.types.update.Update object at 0x7fc46e6ad9a0>,)
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x7fc4716be370>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x7...
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
                 │    │                       │      │      └ <aiogram.types.fields.Field object at 0x7fc46ffb4670>
                 │    │                       │      └ <aiogram.types.update.Update object at 0x7fc46e6ad9a0>
                 │    │                       └ <function Handler.notify at 0x7fc46ff2a310>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x7fc470953100>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x7fc4716be370>
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {'user': <database.user_repo.UserRepository object at 0x7fc46f383be0>, '_': {'choose_account_to_delete': 'Выбери какой аккаун...
                     │           │        └ (<aiogram.types.callback_query.CallbackQuery object at 0x7fc46e6805e0>,)
                     │           └ <function account_cabinet_callback_handler at 0x7fc46f6e0160>
                     └ Handler.HandlerObj(handler=<function account_cabinet_callback_handler at 0x7fc46f6e0160>, spec=FullArgSpec(args=['query', 'ca...

  File "/app/handlers/callback/account_cabinet_handler.py", line 70, in account_cabinet_callback_handler
    account_name=account.username
                 └ None

AttributeError: 'NoneType' object has no attribute 'username'`

where to fix

https://github.com/Forevka/Emcd/blob/master/handlers/callback/account_cabinet_handler.py#L66

**Comment by Forevka** [comment]
fixed
